### PR TITLE
Added collision detection

### PR DESCRIPTION
**Pull request by KostasThan**
For #1 
Summary:
1. Added collision detection between zombies and player. 
1. Player cannot escape the window.
1. Generated a versionId for the Window.java

Note: Since you dont have as a parameter the windows width-height to the player class i hard coded the values.
If the window is resized they player will stop significally shorter than the available "map".

Have fun!

### CODE REVIEW

**Review by KT360 — APPROVED** [review]
Woah, this is awesome! I did not expect someone to pick up this random little game.

I was going to leave it for later, but now this is definitely worth expanding upon!

**Comment by KostasThan** [comment]
I am glad that brought joy. In my humble opinion you should make every field private and generate getters. It is proper OCP and OOP programming. Also helps **a lot** with debugging. If you want create an issue and i might pick up from there.
Cheers!

**Comment by KT360** [comment]
For sure!

**Comment by KT360** [comment]
Hello again,

Not sure if this message will reach you, but I have a few questions and would like to receive some feedback on some of my projects as other things.

**Pull request merged**
